// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PostDeviceMountpointsReader is a Reader for the PostDeviceMountpoints structure.
type PostDeviceMountpointsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostDeviceMountpointsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostDeviceMountpointsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostDeviceMountpointsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostDeviceMountpointsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPostDeviceMountpointsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPostDeviceMountpointsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 405:
		result := NewPostDeviceMountpointsMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 410:
		result := NewPostDeviceMountpointsGone()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostDeviceMountpointsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewPostDeviceMountpointsServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostDeviceMountpointsOK creates a PostDeviceMountpointsOK with default headers values
func NewPostDeviceMountpointsOK() *PostDeviceMountpointsOK {
	return &PostDeviceMountpointsOK{}
}

/*PostDeviceMountpointsOK handles this case with default header values.

The above command returns results like this:
*/
type PostDeviceMountpointsOK struct {
	Payload *PostDeviceMountpointsOKBody
}

func (o *PostDeviceMountpointsOK) Error() string {
	return fmt.Sprintf("[POST /api/1.0/device/mountpoints/][%d] postDeviceMountpointsOK  %+v", 200, o.Payload)
}

func (o *PostDeviceMountpointsOK) GetPayload() *PostDeviceMountpointsOKBody {
	return o.Payload
}

func (o *PostDeviceMountpointsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PostDeviceMountpointsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostDeviceMountpointsBadRequest creates a PostDeviceMountpointsBadRequest with default headers values
func NewPostDeviceMountpointsBadRequest() *PostDeviceMountpointsBadRequest {
	return &PostDeviceMountpointsBadRequest{}
}

/*PostDeviceMountpointsBadRequest handles this case with default header values.

Bad Request (A validation exception has occurred.)
*/
type PostDeviceMountpointsBadRequest struct {
}

func (o *PostDeviceMountpointsBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/1.0/device/mountpoints/][%d] postDeviceMountpointsBadRequest ", 400)
}

func (o *PostDeviceMountpointsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostDeviceMountpointsUnauthorized creates a PostDeviceMountpointsUnauthorized with default headers values
func NewPostDeviceMountpointsUnauthorized() *PostDeviceMountpointsUnauthorized {
	return &PostDeviceMountpointsUnauthorized{}
}

/*PostDeviceMountpointsUnauthorized handles this case with default header values.

Unauthorized (Your credentials suck)
*/
type PostDeviceMountpointsUnauthorized struct {
}

func (o *PostDeviceMountpointsUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api/1.0/device/mountpoints/][%d] postDeviceMountpointsUnauthorized ", 401)
}

func (o *PostDeviceMountpointsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostDeviceMountpointsForbidden creates a PostDeviceMountpointsForbidden with default headers values
func NewPostDeviceMountpointsForbidden() *PostDeviceMountpointsForbidden {
	return &PostDeviceMountpointsForbidden{}
}

/*PostDeviceMountpointsForbidden handles this case with default header values.

Forbidden (The resource requested is hidden)
*/
type PostDeviceMountpointsForbidden struct {
}

func (o *PostDeviceMountpointsForbidden) Error() string {
	return fmt.Sprintf("[POST /api/1.0/device/mountpoints/][%d] postDeviceMountpointsForbidden ", 403)
}

func (o *PostDeviceMountpointsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostDeviceMountpointsNotFound creates a PostDeviceMountpointsNotFound with default headers values
func NewPostDeviceMountpointsNotFound() *PostDeviceMountpointsNotFound {
	return &PostDeviceMountpointsNotFound{}
}

/*PostDeviceMountpointsNotFound handles this case with default header values.

Not Found (The specified resource could not be found)
*/
type PostDeviceMountpointsNotFound struct {
}

func (o *PostDeviceMountpointsNotFound) Error() string {
	return fmt.Sprintf("[POST /api/1.0/device/mountpoints/][%d] postDeviceMountpointsNotFound ", 404)
}

func (o *PostDeviceMountpointsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostDeviceMountpointsMethodNotAllowed creates a PostDeviceMountpointsMethodNotAllowed with default headers values
func NewPostDeviceMountpointsMethodNotAllowed() *PostDeviceMountpointsMethodNotAllowed {
	return &PostDeviceMountpointsMethodNotAllowed{}
}

/*PostDeviceMountpointsMethodNotAllowed handles this case with default header values.

Method Not Allowed (You tried to access a resource with an invalid method)
*/
type PostDeviceMountpointsMethodNotAllowed struct {
}

func (o *PostDeviceMountpointsMethodNotAllowed) Error() string {
	return fmt.Sprintf("[POST /api/1.0/device/mountpoints/][%d] postDeviceMountpointsMethodNotAllowed ", 405)
}

func (o *PostDeviceMountpointsMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostDeviceMountpointsGone creates a PostDeviceMountpointsGone with default headers values
func NewPostDeviceMountpointsGone() *PostDeviceMountpointsGone {
	return &PostDeviceMountpointsGone{}
}

/*PostDeviceMountpointsGone handles this case with default header values.

Gone (The resource requested has been removed from our servers)
*/
type PostDeviceMountpointsGone struct {
}

func (o *PostDeviceMountpointsGone) Error() string {
	return fmt.Sprintf("[POST /api/1.0/device/mountpoints/][%d] postDeviceMountpointsGone ", 410)
}

func (o *PostDeviceMountpointsGone) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostDeviceMountpointsInternalServerError creates a PostDeviceMountpointsInternalServerError with default headers values
func NewPostDeviceMountpointsInternalServerError() *PostDeviceMountpointsInternalServerError {
	return &PostDeviceMountpointsInternalServerError{}
}

/*PostDeviceMountpointsInternalServerError handles this case with default header values.

Internal Server Error (Some parameter missing or issue with the server. Check with returned “msg” from the call.)
*/
type PostDeviceMountpointsInternalServerError struct {
}

func (o *PostDeviceMountpointsInternalServerError) Error() string {
	return fmt.Sprintf("[POST /api/1.0/device/mountpoints/][%d] postDeviceMountpointsInternalServerError ", 500)
}

func (o *PostDeviceMountpointsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostDeviceMountpointsServiceUnavailable creates a PostDeviceMountpointsServiceUnavailable with default headers values
func NewPostDeviceMountpointsServiceUnavailable() *PostDeviceMountpointsServiceUnavailable {
	return &PostDeviceMountpointsServiceUnavailable{}
}

/*PostDeviceMountpointsServiceUnavailable handles this case with default header values.

Service Unavailable (Please check if your Device42 instance is working normally.)
*/
type PostDeviceMountpointsServiceUnavailable struct {
}

func (o *PostDeviceMountpointsServiceUnavailable) Error() string {
	return fmt.Sprintf("[POST /api/1.0/device/mountpoints/][%d] postDeviceMountpointsServiceUnavailable ", 503)
}

func (o *PostDeviceMountpointsServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*PostDeviceMountpointsOKBody post device mountpoints o k body
swagger:model PostDeviceMountpointsOKBody
*/
type PostDeviceMountpointsOKBody struct {

	// code
	Code interface{} `json:"code,omitempty"`

	// msg
	Msg interface{} `json:"msg,omitempty"`
}

// Validate validates this post device mountpoints o k body
func (o *PostDeviceMountpointsOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostDeviceMountpointsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostDeviceMountpointsOKBody) UnmarshalBinary(b []byte) error {
	var res PostDeviceMountpointsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
