// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/mjpitz/libdevice42/models"
)

// PostCloudInstanceDeviceReader is a Reader for the PostCloudInstanceDevice structure.
type PostCloudInstanceDeviceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostCloudInstanceDeviceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostCloudInstanceDeviceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostCloudInstanceDeviceBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostCloudInstanceDeviceUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPostCloudInstanceDeviceForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPostCloudInstanceDeviceNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 405:
		result := NewPostCloudInstanceDeviceMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 410:
		result := NewPostCloudInstanceDeviceGone()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostCloudInstanceDeviceInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewPostCloudInstanceDeviceServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostCloudInstanceDeviceOK creates a PostCloudInstanceDeviceOK with default headers values
func NewPostCloudInstanceDeviceOK() *PostCloudInstanceDeviceOK {
	return &PostCloudInstanceDeviceOK{}
}

/*PostCloudInstanceDeviceOK handles this case with default header values.

The above command returns results like this:
*/
type PostCloudInstanceDeviceOK struct {
	Payload *PostCloudInstanceDeviceOKBody
}

func (o *PostCloudInstanceDeviceOK) Error() string {
	return fmt.Sprintf("[POST /api/1.0/device/cloud_instance/][%d] postCloudInstanceDeviceOK  %+v", 200, o.Payload)
}

func (o *PostCloudInstanceDeviceOK) GetPayload() *PostCloudInstanceDeviceOKBody {
	return o.Payload
}

func (o *PostCloudInstanceDeviceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PostCloudInstanceDeviceOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostCloudInstanceDeviceBadRequest creates a PostCloudInstanceDeviceBadRequest with default headers values
func NewPostCloudInstanceDeviceBadRequest() *PostCloudInstanceDeviceBadRequest {
	return &PostCloudInstanceDeviceBadRequest{}
}

/*PostCloudInstanceDeviceBadRequest handles this case with default header values.

Bad Request (A validation exception has occurred.)
*/
type PostCloudInstanceDeviceBadRequest struct {
}

func (o *PostCloudInstanceDeviceBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/1.0/device/cloud_instance/][%d] postCloudInstanceDeviceBadRequest ", 400)
}

func (o *PostCloudInstanceDeviceBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostCloudInstanceDeviceUnauthorized creates a PostCloudInstanceDeviceUnauthorized with default headers values
func NewPostCloudInstanceDeviceUnauthorized() *PostCloudInstanceDeviceUnauthorized {
	return &PostCloudInstanceDeviceUnauthorized{}
}

/*PostCloudInstanceDeviceUnauthorized handles this case with default header values.

Unauthorized (Your credentials suck)
*/
type PostCloudInstanceDeviceUnauthorized struct {
}

func (o *PostCloudInstanceDeviceUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api/1.0/device/cloud_instance/][%d] postCloudInstanceDeviceUnauthorized ", 401)
}

func (o *PostCloudInstanceDeviceUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostCloudInstanceDeviceForbidden creates a PostCloudInstanceDeviceForbidden with default headers values
func NewPostCloudInstanceDeviceForbidden() *PostCloudInstanceDeviceForbidden {
	return &PostCloudInstanceDeviceForbidden{}
}

/*PostCloudInstanceDeviceForbidden handles this case with default header values.

Forbidden (The resource requested is hidden)
*/
type PostCloudInstanceDeviceForbidden struct {
}

func (o *PostCloudInstanceDeviceForbidden) Error() string {
	return fmt.Sprintf("[POST /api/1.0/device/cloud_instance/][%d] postCloudInstanceDeviceForbidden ", 403)
}

func (o *PostCloudInstanceDeviceForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostCloudInstanceDeviceNotFound creates a PostCloudInstanceDeviceNotFound with default headers values
func NewPostCloudInstanceDeviceNotFound() *PostCloudInstanceDeviceNotFound {
	return &PostCloudInstanceDeviceNotFound{}
}

/*PostCloudInstanceDeviceNotFound handles this case with default header values.

Not Found (The specified resource could not be found)
*/
type PostCloudInstanceDeviceNotFound struct {
}

func (o *PostCloudInstanceDeviceNotFound) Error() string {
	return fmt.Sprintf("[POST /api/1.0/device/cloud_instance/][%d] postCloudInstanceDeviceNotFound ", 404)
}

func (o *PostCloudInstanceDeviceNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostCloudInstanceDeviceMethodNotAllowed creates a PostCloudInstanceDeviceMethodNotAllowed with default headers values
func NewPostCloudInstanceDeviceMethodNotAllowed() *PostCloudInstanceDeviceMethodNotAllowed {
	return &PostCloudInstanceDeviceMethodNotAllowed{}
}

/*PostCloudInstanceDeviceMethodNotAllowed handles this case with default header values.

Method Not Allowed (You tried to access a resource with an invalid method)
*/
type PostCloudInstanceDeviceMethodNotAllowed struct {
}

func (o *PostCloudInstanceDeviceMethodNotAllowed) Error() string {
	return fmt.Sprintf("[POST /api/1.0/device/cloud_instance/][%d] postCloudInstanceDeviceMethodNotAllowed ", 405)
}

func (o *PostCloudInstanceDeviceMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostCloudInstanceDeviceGone creates a PostCloudInstanceDeviceGone with default headers values
func NewPostCloudInstanceDeviceGone() *PostCloudInstanceDeviceGone {
	return &PostCloudInstanceDeviceGone{}
}

/*PostCloudInstanceDeviceGone handles this case with default header values.

Gone (The resource requested has been removed from our servers)
*/
type PostCloudInstanceDeviceGone struct {
}

func (o *PostCloudInstanceDeviceGone) Error() string {
	return fmt.Sprintf("[POST /api/1.0/device/cloud_instance/][%d] postCloudInstanceDeviceGone ", 410)
}

func (o *PostCloudInstanceDeviceGone) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostCloudInstanceDeviceInternalServerError creates a PostCloudInstanceDeviceInternalServerError with default headers values
func NewPostCloudInstanceDeviceInternalServerError() *PostCloudInstanceDeviceInternalServerError {
	return &PostCloudInstanceDeviceInternalServerError{}
}

/*PostCloudInstanceDeviceInternalServerError handles this case with default header values.

Internal Server Error (Some parameter missing or issue with the server. Check with returned “msg” from the call.)
*/
type PostCloudInstanceDeviceInternalServerError struct {
}

func (o *PostCloudInstanceDeviceInternalServerError) Error() string {
	return fmt.Sprintf("[POST /api/1.0/device/cloud_instance/][%d] postCloudInstanceDeviceInternalServerError ", 500)
}

func (o *PostCloudInstanceDeviceInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostCloudInstanceDeviceServiceUnavailable creates a PostCloudInstanceDeviceServiceUnavailable with default headers values
func NewPostCloudInstanceDeviceServiceUnavailable() *PostCloudInstanceDeviceServiceUnavailable {
	return &PostCloudInstanceDeviceServiceUnavailable{}
}

/*PostCloudInstanceDeviceServiceUnavailable handles this case with default header values.

Service Unavailable (Please check if your Device42 instance is working normally.)
*/
type PostCloudInstanceDeviceServiceUnavailable struct {
}

func (o *PostCloudInstanceDeviceServiceUnavailable) Error() string {
	return fmt.Sprintf("[POST /api/1.0/device/cloud_instance/][%d] postCloudInstanceDeviceServiceUnavailable ", 503)
}

func (o *PostCloudInstanceDeviceServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*PostCloudInstanceDeviceOKBody The above command returns results like this:
swagger:model PostCloudInstanceDeviceOKBody
*/
type PostCloudInstanceDeviceOKBody struct {

	// devices
	Devices models.Devices `json:"devices"`
}

// Validate validates this post cloud instance device o k body
func (o *PostCloudInstanceDeviceOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateDevices(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostCloudInstanceDeviceOKBody) validateDevices(formats strfmt.Registry) error {

	if swag.IsZero(o.Devices) { // not required
		return nil
	}

	if err := o.Devices.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("postCloudInstanceDeviceOK" + "." + "devices")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *PostCloudInstanceDeviceOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostCloudInstanceDeviceOKBody) UnmarshalBinary(b []byte) error {
	var res PostCloudInstanceDeviceOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
