// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PutCustomFieldReader is a Reader for the PutCustomField structure.
type PutCustomFieldReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutCustomFieldReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutCustomFieldOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPutCustomFieldBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPutCustomFieldUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPutCustomFieldForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPutCustomFieldNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 405:
		result := NewPutCustomFieldMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 410:
		result := NewPutCustomFieldGone()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPutCustomFieldInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewPutCustomFieldServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutCustomFieldOK creates a PutCustomFieldOK with default headers values
func NewPutCustomFieldOK() *PutCustomFieldOK {
	return &PutCustomFieldOK{}
}

/*PutCustomFieldOK handles this case with default header values.

The above command returns results like this:
*/
type PutCustomFieldOK struct {
	Payload *PutCustomFieldOKBody
}

func (o *PutCustomFieldOK) Error() string {
	return fmt.Sprintf("[PUT /api/1.0/device/custom_field/][%d] putCustomFieldOK  %+v", 200, o.Payload)
}

func (o *PutCustomFieldOK) GetPayload() *PutCustomFieldOKBody {
	return o.Payload
}

func (o *PutCustomFieldOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PutCustomFieldOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutCustomFieldBadRequest creates a PutCustomFieldBadRequest with default headers values
func NewPutCustomFieldBadRequest() *PutCustomFieldBadRequest {
	return &PutCustomFieldBadRequest{}
}

/*PutCustomFieldBadRequest handles this case with default header values.

Bad Request (A validation exception has occurred.)
*/
type PutCustomFieldBadRequest struct {
}

func (o *PutCustomFieldBadRequest) Error() string {
	return fmt.Sprintf("[PUT /api/1.0/device/custom_field/][%d] putCustomFieldBadRequest ", 400)
}

func (o *PutCustomFieldBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutCustomFieldUnauthorized creates a PutCustomFieldUnauthorized with default headers values
func NewPutCustomFieldUnauthorized() *PutCustomFieldUnauthorized {
	return &PutCustomFieldUnauthorized{}
}

/*PutCustomFieldUnauthorized handles this case with default header values.

Unauthorized (Your credentials suck)
*/
type PutCustomFieldUnauthorized struct {
}

func (o *PutCustomFieldUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /api/1.0/device/custom_field/][%d] putCustomFieldUnauthorized ", 401)
}

func (o *PutCustomFieldUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutCustomFieldForbidden creates a PutCustomFieldForbidden with default headers values
func NewPutCustomFieldForbidden() *PutCustomFieldForbidden {
	return &PutCustomFieldForbidden{}
}

/*PutCustomFieldForbidden handles this case with default header values.

Forbidden (The resource requested is hidden)
*/
type PutCustomFieldForbidden struct {
}

func (o *PutCustomFieldForbidden) Error() string {
	return fmt.Sprintf("[PUT /api/1.0/device/custom_field/][%d] putCustomFieldForbidden ", 403)
}

func (o *PutCustomFieldForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutCustomFieldNotFound creates a PutCustomFieldNotFound with default headers values
func NewPutCustomFieldNotFound() *PutCustomFieldNotFound {
	return &PutCustomFieldNotFound{}
}

/*PutCustomFieldNotFound handles this case with default header values.

Not Found (The specified resource could not be found)
*/
type PutCustomFieldNotFound struct {
}

func (o *PutCustomFieldNotFound) Error() string {
	return fmt.Sprintf("[PUT /api/1.0/device/custom_field/][%d] putCustomFieldNotFound ", 404)
}

func (o *PutCustomFieldNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutCustomFieldMethodNotAllowed creates a PutCustomFieldMethodNotAllowed with default headers values
func NewPutCustomFieldMethodNotAllowed() *PutCustomFieldMethodNotAllowed {
	return &PutCustomFieldMethodNotAllowed{}
}

/*PutCustomFieldMethodNotAllowed handles this case with default header values.

Method Not Allowed (You tried to access a resource with an invalid method)
*/
type PutCustomFieldMethodNotAllowed struct {
}

func (o *PutCustomFieldMethodNotAllowed) Error() string {
	return fmt.Sprintf("[PUT /api/1.0/device/custom_field/][%d] putCustomFieldMethodNotAllowed ", 405)
}

func (o *PutCustomFieldMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutCustomFieldGone creates a PutCustomFieldGone with default headers values
func NewPutCustomFieldGone() *PutCustomFieldGone {
	return &PutCustomFieldGone{}
}

/*PutCustomFieldGone handles this case with default header values.

Gone (The resource requested has been removed from our servers)
*/
type PutCustomFieldGone struct {
}

func (o *PutCustomFieldGone) Error() string {
	return fmt.Sprintf("[PUT /api/1.0/device/custom_field/][%d] putCustomFieldGone ", 410)
}

func (o *PutCustomFieldGone) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutCustomFieldInternalServerError creates a PutCustomFieldInternalServerError with default headers values
func NewPutCustomFieldInternalServerError() *PutCustomFieldInternalServerError {
	return &PutCustomFieldInternalServerError{}
}

/*PutCustomFieldInternalServerError handles this case with default header values.

Internal Server Error (Some parameter missing or issue with the server. Check with returned “msg” from the call.)
*/
type PutCustomFieldInternalServerError struct {
}

func (o *PutCustomFieldInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /api/1.0/device/custom_field/][%d] putCustomFieldInternalServerError ", 500)
}

func (o *PutCustomFieldInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutCustomFieldServiceUnavailable creates a PutCustomFieldServiceUnavailable with default headers values
func NewPutCustomFieldServiceUnavailable() *PutCustomFieldServiceUnavailable {
	return &PutCustomFieldServiceUnavailable{}
}

/*PutCustomFieldServiceUnavailable handles this case with default header values.

Service Unavailable (Please check if your Device42 instance is working normally.)
*/
type PutCustomFieldServiceUnavailable struct {
}

func (o *PutCustomFieldServiceUnavailable) Error() string {
	return fmt.Sprintf("[PUT /api/1.0/device/custom_field/][%d] putCustomFieldServiceUnavailable ", 503)
}

func (o *PutCustomFieldServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*PutCustomFieldOKBody put custom field o k body
swagger:model PutCustomFieldOKBody
*/
type PutCustomFieldOKBody struct {

	// code
	Code interface{} `json:"code,omitempty"`

	// msg
	Msg interface{} `json:"msg,omitempty"`
}

// Validate validates this put custom field o k body
func (o *PutCustomFieldOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PutCustomFieldOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PutCustomFieldOKBody) UnmarshalBinary(b []byte) error {
	var res PutCustomFieldOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
