// Code generated by go-swagger; DO NOT EDIT.

package services

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetServicePortsParams creates a new GetServicePortsParams object
// with the default values initialized.
func NewGetServicePortsParams() *GetServicePortsParams {
	var ()
	return &GetServicePortsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetServicePortsParamsWithTimeout creates a new GetServicePortsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetServicePortsParamsWithTimeout(timeout time.Duration) *GetServicePortsParams {
	var ()
	return &GetServicePortsParams{

		timeout: timeout,
	}
}

// NewGetServicePortsParamsWithContext creates a new GetServicePortsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetServicePortsParamsWithContext(ctx context.Context) *GetServicePortsParams {
	var ()
	return &GetServicePortsParams{

		Context: ctx,
	}
}

// NewGetServicePortsParamsWithHTTPClient creates a new GetServicePortsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetServicePortsParamsWithHTTPClient(client *http.Client) *GetServicePortsParams {
	var ()
	return &GetServicePortsParams{
		HTTPClient: client,
	}
}

/*GetServicePortsParams contains all the parameters to send to the API endpoint
for the get service ports operation typically these are written to a http.Request
*/
type GetServicePortsParams struct {

	/*ID
	  filter by id of the service port

	*/
	ID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get service ports params
func (o *GetServicePortsParams) WithTimeout(timeout time.Duration) *GetServicePortsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get service ports params
func (o *GetServicePortsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get service ports params
func (o *GetServicePortsParams) WithContext(ctx context.Context) *GetServicePortsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get service ports params
func (o *GetServicePortsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get service ports params
func (o *GetServicePortsParams) WithHTTPClient(client *http.Client) *GetServicePortsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get service ports params
func (o *GetServicePortsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get service ports params
func (o *GetServicePortsParams) WithID(id *string) *GetServicePortsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get service ports params
func (o *GetServicePortsParams) SetID(id *string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetServicePortsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ID != nil {

		// query param id
		var qrID string
		if o.ID != nil {
			qrID = *o.ID
		}
		qID := qrID
		if qID != "" {
			if err := r.SetQueryParam("id", qID); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
