// Code generated by go-swagger; DO NOT EDIT.

package ip_a_m

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeleteIPAMsubnetsReader is a Reader for the DeleteIPAMsubnets structure.
type DeleteIPAMsubnetsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteIPAMsubnetsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteIPAMsubnetsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteIPAMsubnetsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteIPAMsubnetsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteIPAMsubnetsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteIPAMsubnetsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 405:
		result := NewDeleteIPAMsubnetsMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 410:
		result := NewDeleteIPAMsubnetsGone()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteIPAMsubnetsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewDeleteIPAMsubnetsServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteIPAMsubnetsOK creates a DeleteIPAMsubnetsOK with default headers values
func NewDeleteIPAMsubnetsOK() *DeleteIPAMsubnetsOK {
	return &DeleteIPAMsubnetsOK{}
}

/*DeleteIPAMsubnetsOK handles this case with default header values.

The above command returns JSON structured like this:
*/
type DeleteIPAMsubnetsOK struct {
	Payload *DeleteIPAMsubnetsOKBody
}

func (o *DeleteIPAMsubnetsOK) Error() string {
	return fmt.Sprintf("[DELETE /api/1.0/subnets/{subnet_id}/][%d] deleteIpAMsubnetsOK  %+v", 200, o.Payload)
}

func (o *DeleteIPAMsubnetsOK) GetPayload() *DeleteIPAMsubnetsOKBody {
	return o.Payload
}

func (o *DeleteIPAMsubnetsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(DeleteIPAMsubnetsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteIPAMsubnetsBadRequest creates a DeleteIPAMsubnetsBadRequest with default headers values
func NewDeleteIPAMsubnetsBadRequest() *DeleteIPAMsubnetsBadRequest {
	return &DeleteIPAMsubnetsBadRequest{}
}

/*DeleteIPAMsubnetsBadRequest handles this case with default header values.

Bad Request (A validation exception has occurred.)
*/
type DeleteIPAMsubnetsBadRequest struct {
}

func (o *DeleteIPAMsubnetsBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /api/1.0/subnets/{subnet_id}/][%d] deleteIpAMsubnetsBadRequest ", 400)
}

func (o *DeleteIPAMsubnetsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteIPAMsubnetsUnauthorized creates a DeleteIPAMsubnetsUnauthorized with default headers values
func NewDeleteIPAMsubnetsUnauthorized() *DeleteIPAMsubnetsUnauthorized {
	return &DeleteIPAMsubnetsUnauthorized{}
}

/*DeleteIPAMsubnetsUnauthorized handles this case with default header values.

Unauthorized (Your credentials suck)
*/
type DeleteIPAMsubnetsUnauthorized struct {
}

func (o *DeleteIPAMsubnetsUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /api/1.0/subnets/{subnet_id}/][%d] deleteIpAMsubnetsUnauthorized ", 401)
}

func (o *DeleteIPAMsubnetsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteIPAMsubnetsForbidden creates a DeleteIPAMsubnetsForbidden with default headers values
func NewDeleteIPAMsubnetsForbidden() *DeleteIPAMsubnetsForbidden {
	return &DeleteIPAMsubnetsForbidden{}
}

/*DeleteIPAMsubnetsForbidden handles this case with default header values.

Forbidden (The resource requested is hidden)
*/
type DeleteIPAMsubnetsForbidden struct {
}

func (o *DeleteIPAMsubnetsForbidden) Error() string {
	return fmt.Sprintf("[DELETE /api/1.0/subnets/{subnet_id}/][%d] deleteIpAMsubnetsForbidden ", 403)
}

func (o *DeleteIPAMsubnetsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteIPAMsubnetsNotFound creates a DeleteIPAMsubnetsNotFound with default headers values
func NewDeleteIPAMsubnetsNotFound() *DeleteIPAMsubnetsNotFound {
	return &DeleteIPAMsubnetsNotFound{}
}

/*DeleteIPAMsubnetsNotFound handles this case with default header values.

Not Found (The specified resource could not be found)
*/
type DeleteIPAMsubnetsNotFound struct {
}

func (o *DeleteIPAMsubnetsNotFound) Error() string {
	return fmt.Sprintf("[DELETE /api/1.0/subnets/{subnet_id}/][%d] deleteIpAMsubnetsNotFound ", 404)
}

func (o *DeleteIPAMsubnetsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteIPAMsubnetsMethodNotAllowed creates a DeleteIPAMsubnetsMethodNotAllowed with default headers values
func NewDeleteIPAMsubnetsMethodNotAllowed() *DeleteIPAMsubnetsMethodNotAllowed {
	return &DeleteIPAMsubnetsMethodNotAllowed{}
}

/*DeleteIPAMsubnetsMethodNotAllowed handles this case with default header values.

Method Not Allowed (You tried to access a resource with an invalid method)
*/
type DeleteIPAMsubnetsMethodNotAllowed struct {
}

func (o *DeleteIPAMsubnetsMethodNotAllowed) Error() string {
	return fmt.Sprintf("[DELETE /api/1.0/subnets/{subnet_id}/][%d] deleteIpAMsubnetsMethodNotAllowed ", 405)
}

func (o *DeleteIPAMsubnetsMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteIPAMsubnetsGone creates a DeleteIPAMsubnetsGone with default headers values
func NewDeleteIPAMsubnetsGone() *DeleteIPAMsubnetsGone {
	return &DeleteIPAMsubnetsGone{}
}

/*DeleteIPAMsubnetsGone handles this case with default header values.

Gone (The resource requested has been removed from our servers)
*/
type DeleteIPAMsubnetsGone struct {
}

func (o *DeleteIPAMsubnetsGone) Error() string {
	return fmt.Sprintf("[DELETE /api/1.0/subnets/{subnet_id}/][%d] deleteIpAMsubnetsGone ", 410)
}

func (o *DeleteIPAMsubnetsGone) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteIPAMsubnetsInternalServerError creates a DeleteIPAMsubnetsInternalServerError with default headers values
func NewDeleteIPAMsubnetsInternalServerError() *DeleteIPAMsubnetsInternalServerError {
	return &DeleteIPAMsubnetsInternalServerError{}
}

/*DeleteIPAMsubnetsInternalServerError handles this case with default header values.

Internal Server Error (Some parameter missing or issue with the server. Check with returned “msg” from the call.)
*/
type DeleteIPAMsubnetsInternalServerError struct {
}

func (o *DeleteIPAMsubnetsInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /api/1.0/subnets/{subnet_id}/][%d] deleteIpAMsubnetsInternalServerError ", 500)
}

func (o *DeleteIPAMsubnetsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteIPAMsubnetsServiceUnavailable creates a DeleteIPAMsubnetsServiceUnavailable with default headers values
func NewDeleteIPAMsubnetsServiceUnavailable() *DeleteIPAMsubnetsServiceUnavailable {
	return &DeleteIPAMsubnetsServiceUnavailable{}
}

/*DeleteIPAMsubnetsServiceUnavailable handles this case with default header values.

Service Unavailable (Please check if your Device42 instance is working normally.)
*/
type DeleteIPAMsubnetsServiceUnavailable struct {
}

func (o *DeleteIPAMsubnetsServiceUnavailable) Error() string {
	return fmt.Sprintf("[DELETE /api/1.0/subnets/{subnet_id}/][%d] deleteIpAMsubnetsServiceUnavailable ", 503)
}

func (o *DeleteIPAMsubnetsServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*DeleteIPAMsubnetsOKBody delete IP a msubnets o k body
swagger:model DeleteIPAMsubnetsOKBody
*/
type DeleteIPAMsubnetsOKBody struct {

	// deleted
	Deleted interface{} `json:"deleted,omitempty"`

	// id
	ID interface{} `json:"id,omitempty"`
}

// Validate validates this delete IP a msubnets o k body
func (o *DeleteIPAMsubnetsOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteIPAMsubnetsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteIPAMsubnetsOKBody) UnmarshalBinary(b []byte) error {
	var res DeleteIPAMsubnetsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
