// Code generated by go-swagger; DO NOT EDIT.

package ip_a_m

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PostIPAMTapPortsReader is a Reader for the PostIPAMTapPorts structure.
type PostIPAMTapPortsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostIPAMTapPortsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostIPAMTapPortsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostIPAMTapPortsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostIPAMTapPortsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPostIPAMTapPortsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPostIPAMTapPortsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 405:
		result := NewPostIPAMTapPortsMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 410:
		result := NewPostIPAMTapPortsGone()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostIPAMTapPortsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewPostIPAMTapPortsServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostIPAMTapPortsOK creates a PostIPAMTapPortsOK with default headers values
func NewPostIPAMTapPortsOK() *PostIPAMTapPortsOK {
	return &PostIPAMTapPortsOK{}
}

/*PostIPAMTapPortsOK handles this case with default header values.

The above command returns results like this:
*/
type PostIPAMTapPortsOK struct {
	Payload *PostIPAMTapPortsOKBody
}

func (o *PostIPAMTapPortsOK) Error() string {
	return fmt.Sprintf("[POST /api/1.0/tap_ports/][%d] postIpAMTapPortsOK  %+v", 200, o.Payload)
}

func (o *PostIPAMTapPortsOK) GetPayload() *PostIPAMTapPortsOKBody {
	return o.Payload
}

func (o *PostIPAMTapPortsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PostIPAMTapPortsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostIPAMTapPortsBadRequest creates a PostIPAMTapPortsBadRequest with default headers values
func NewPostIPAMTapPortsBadRequest() *PostIPAMTapPortsBadRequest {
	return &PostIPAMTapPortsBadRequest{}
}

/*PostIPAMTapPortsBadRequest handles this case with default header values.

Bad Request (A validation exception has occurred.)
*/
type PostIPAMTapPortsBadRequest struct {
}

func (o *PostIPAMTapPortsBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/1.0/tap_ports/][%d] postIpAMTapPortsBadRequest ", 400)
}

func (o *PostIPAMTapPortsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostIPAMTapPortsUnauthorized creates a PostIPAMTapPortsUnauthorized with default headers values
func NewPostIPAMTapPortsUnauthorized() *PostIPAMTapPortsUnauthorized {
	return &PostIPAMTapPortsUnauthorized{}
}

/*PostIPAMTapPortsUnauthorized handles this case with default header values.

Unauthorized (Your credentials suck)
*/
type PostIPAMTapPortsUnauthorized struct {
}

func (o *PostIPAMTapPortsUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api/1.0/tap_ports/][%d] postIpAMTapPortsUnauthorized ", 401)
}

func (o *PostIPAMTapPortsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostIPAMTapPortsForbidden creates a PostIPAMTapPortsForbidden with default headers values
func NewPostIPAMTapPortsForbidden() *PostIPAMTapPortsForbidden {
	return &PostIPAMTapPortsForbidden{}
}

/*PostIPAMTapPortsForbidden handles this case with default header values.

Forbidden (The resource requested is hidden)
*/
type PostIPAMTapPortsForbidden struct {
}

func (o *PostIPAMTapPortsForbidden) Error() string {
	return fmt.Sprintf("[POST /api/1.0/tap_ports/][%d] postIpAMTapPortsForbidden ", 403)
}

func (o *PostIPAMTapPortsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostIPAMTapPortsNotFound creates a PostIPAMTapPortsNotFound with default headers values
func NewPostIPAMTapPortsNotFound() *PostIPAMTapPortsNotFound {
	return &PostIPAMTapPortsNotFound{}
}

/*PostIPAMTapPortsNotFound handles this case with default header values.

Not Found (The specified resource could not be found)
*/
type PostIPAMTapPortsNotFound struct {
}

func (o *PostIPAMTapPortsNotFound) Error() string {
	return fmt.Sprintf("[POST /api/1.0/tap_ports/][%d] postIpAMTapPortsNotFound ", 404)
}

func (o *PostIPAMTapPortsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostIPAMTapPortsMethodNotAllowed creates a PostIPAMTapPortsMethodNotAllowed with default headers values
func NewPostIPAMTapPortsMethodNotAllowed() *PostIPAMTapPortsMethodNotAllowed {
	return &PostIPAMTapPortsMethodNotAllowed{}
}

/*PostIPAMTapPortsMethodNotAllowed handles this case with default header values.

Method Not Allowed (You tried to access a resource with an invalid method)
*/
type PostIPAMTapPortsMethodNotAllowed struct {
}

func (o *PostIPAMTapPortsMethodNotAllowed) Error() string {
	return fmt.Sprintf("[POST /api/1.0/tap_ports/][%d] postIpAMTapPortsMethodNotAllowed ", 405)
}

func (o *PostIPAMTapPortsMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostIPAMTapPortsGone creates a PostIPAMTapPortsGone with default headers values
func NewPostIPAMTapPortsGone() *PostIPAMTapPortsGone {
	return &PostIPAMTapPortsGone{}
}

/*PostIPAMTapPortsGone handles this case with default header values.

Gone (The resource requested has been removed from our servers)
*/
type PostIPAMTapPortsGone struct {
}

func (o *PostIPAMTapPortsGone) Error() string {
	return fmt.Sprintf("[POST /api/1.0/tap_ports/][%d] postIpAMTapPortsGone ", 410)
}

func (o *PostIPAMTapPortsGone) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostIPAMTapPortsInternalServerError creates a PostIPAMTapPortsInternalServerError with default headers values
func NewPostIPAMTapPortsInternalServerError() *PostIPAMTapPortsInternalServerError {
	return &PostIPAMTapPortsInternalServerError{}
}

/*PostIPAMTapPortsInternalServerError handles this case with default header values.

Internal Server Error (Some parameter missing or issue with the server. Check with returned “msg” from the call.)
*/
type PostIPAMTapPortsInternalServerError struct {
}

func (o *PostIPAMTapPortsInternalServerError) Error() string {
	return fmt.Sprintf("[POST /api/1.0/tap_ports/][%d] postIpAMTapPortsInternalServerError ", 500)
}

func (o *PostIPAMTapPortsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostIPAMTapPortsServiceUnavailable creates a PostIPAMTapPortsServiceUnavailable with default headers values
func NewPostIPAMTapPortsServiceUnavailable() *PostIPAMTapPortsServiceUnavailable {
	return &PostIPAMTapPortsServiceUnavailable{}
}

/*PostIPAMTapPortsServiceUnavailable handles this case with default header values.

Service Unavailable (Please check if your Device42 instance is working normally.)
*/
type PostIPAMTapPortsServiceUnavailable struct {
}

func (o *PostIPAMTapPortsServiceUnavailable) Error() string {
	return fmt.Sprintf("[POST /api/1.0/tap_ports/][%d] postIpAMTapPortsServiceUnavailable ", 503)
}

func (o *PostIPAMTapPortsServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*PostIPAMTapPortsOKBody post IP a m tap ports o k body
swagger:model PostIPAMTapPortsOKBody
*/
type PostIPAMTapPortsOKBody struct {

	// code
	Code interface{} `json:"code,omitempty"`

	// msg
	Msg interface{} `json:"msg,omitempty"`
}

// Validate validates this post IP a m tap ports o k body
func (o *PostIPAMTapPortsOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostIPAMTapPortsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostIPAMTapPortsOKBody) UnmarshalBinary(b []byte) error {
	var res PostIPAMTapPortsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
