// Code generated by go-swagger; DO NOT EDIT.

package ip_a_m

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPutIPAMsubnetcategoryParams creates a new PutIPAMsubnetcategoryParams object
// with the default values initialized.
func NewPutIPAMsubnetcategoryParams() *PutIPAMsubnetcategoryParams {
	var ()
	return &PutIPAMsubnetcategoryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutIPAMsubnetcategoryParamsWithTimeout creates a new PutIPAMsubnetcategoryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutIPAMsubnetcategoryParamsWithTimeout(timeout time.Duration) *PutIPAMsubnetcategoryParams {
	var ()
	return &PutIPAMsubnetcategoryParams{

		timeout: timeout,
	}
}

// NewPutIPAMsubnetcategoryParamsWithContext creates a new PutIPAMsubnetcategoryParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutIPAMsubnetcategoryParamsWithContext(ctx context.Context) *PutIPAMsubnetcategoryParams {
	var ()
	return &PutIPAMsubnetcategoryParams{

		Context: ctx,
	}
}

// NewPutIPAMsubnetcategoryParamsWithHTTPClient creates a new PutIPAMsubnetcategoryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutIPAMsubnetcategoryParamsWithHTTPClient(client *http.Client) *PutIPAMsubnetcategoryParams {
	var ()
	return &PutIPAMsubnetcategoryParams{
		HTTPClient: client,
	}
}

/*PutIPAMsubnetcategoryParams contains all the parameters to send to the API endpoint
for the put IP a msubnetcategory operation typically these are written to a http.Request
*/
type PutIPAMsubnetcategoryParams struct {

	/*Description*/
	Description *string
	/*Groups
	  If multitenancy is on, admin groups that have access to this object are specified here, e.g. Prod_East:no,Corp:yes specifies that the admin groups for this object are Prod_East with view only permission and Corp with change permission. If this parameter is present with no value, all groups are deleted.

	*/
	Groups *string
	/*IsItDefault
	  yes or no. Defaults to no. Only one category can be yes. If yes, this is the subnet category to use if none specified in an API or auto-discovery update.

	*/
	IsItDefault *string
	/*Name
	  Name of the Subnet Category

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put IP a msubnetcategory params
func (o *PutIPAMsubnetcategoryParams) WithTimeout(timeout time.Duration) *PutIPAMsubnetcategoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put IP a msubnetcategory params
func (o *PutIPAMsubnetcategoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put IP a msubnetcategory params
func (o *PutIPAMsubnetcategoryParams) WithContext(ctx context.Context) *PutIPAMsubnetcategoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put IP a msubnetcategory params
func (o *PutIPAMsubnetcategoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put IP a msubnetcategory params
func (o *PutIPAMsubnetcategoryParams) WithHTTPClient(client *http.Client) *PutIPAMsubnetcategoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put IP a msubnetcategory params
func (o *PutIPAMsubnetcategoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDescription adds the description to the put IP a msubnetcategory params
func (o *PutIPAMsubnetcategoryParams) WithDescription(description *string) *PutIPAMsubnetcategoryParams {
	o.SetDescription(description)
	return o
}

// SetDescription adds the description to the put IP a msubnetcategory params
func (o *PutIPAMsubnetcategoryParams) SetDescription(description *string) {
	o.Description = description
}

// WithGroups adds the groups to the put IP a msubnetcategory params
func (o *PutIPAMsubnetcategoryParams) WithGroups(groups *string) *PutIPAMsubnetcategoryParams {
	o.SetGroups(groups)
	return o
}

// SetGroups adds the groups to the put IP a msubnetcategory params
func (o *PutIPAMsubnetcategoryParams) SetGroups(groups *string) {
	o.Groups = groups
}

// WithIsItDefault adds the isItDefault to the put IP a msubnetcategory params
func (o *PutIPAMsubnetcategoryParams) WithIsItDefault(isItDefault *string) *PutIPAMsubnetcategoryParams {
	o.SetIsItDefault(isItDefault)
	return o
}

// SetIsItDefault adds the isItDefault to the put IP a msubnetcategory params
func (o *PutIPAMsubnetcategoryParams) SetIsItDefault(isItDefault *string) {
	o.IsItDefault = isItDefault
}

// WithName adds the name to the put IP a msubnetcategory params
func (o *PutIPAMsubnetcategoryParams) WithName(name string) *PutIPAMsubnetcategoryParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the put IP a msubnetcategory params
func (o *PutIPAMsubnetcategoryParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *PutIPAMsubnetcategoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Description != nil {

		// form param description
		var frDescription string
		if o.Description != nil {
			frDescription = *o.Description
		}
		fDescription := frDescription
		if fDescription != "" {
			if err := r.SetFormParam("description", fDescription); err != nil {
				return err
			}
		}

	}

	if o.Groups != nil {

		// form param groups
		var frGroups string
		if o.Groups != nil {
			frGroups = *o.Groups
		}
		fGroups := frGroups
		if fGroups != "" {
			if err := r.SetFormParam("groups", fGroups); err != nil {
				return err
			}
		}

	}

	if o.IsItDefault != nil {

		// form param is_it_default
		var frIsItDefault string
		if o.IsItDefault != nil {
			frIsItDefault = *o.IsItDefault
		}
		fIsItDefault := frIsItDefault
		if fIsItDefault != "" {
			if err := r.SetFormParam("is_it_default", fIsItDefault); err != nil {
				return err
			}
		}

	}

	// form param name
	frName := o.Name
	fName := frName
	if fName != "" {
		if err := r.SetFormParam("name", fName); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
