// Code generated by go-swagger; DO NOT EDIT.

package ip_a_m

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewPutIPAMvlansParams creates a new PutIPAMvlansParams object
// with the default values initialized.
func NewPutIPAMvlansParams() *PutIPAMvlansParams {
	var ()
	return &PutIPAMvlansParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutIPAMvlansParamsWithTimeout creates a new PutIPAMvlansParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutIPAMvlansParamsWithTimeout(timeout time.Duration) *PutIPAMvlansParams {
	var ()
	return &PutIPAMvlansParams{

		timeout: timeout,
	}
}

// NewPutIPAMvlansParamsWithContext creates a new PutIPAMvlansParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutIPAMvlansParamsWithContext(ctx context.Context) *PutIPAMvlansParams {
	var ()
	return &PutIPAMvlansParams{

		Context: ctx,
	}
}

// NewPutIPAMvlansParamsWithHTTPClient creates a new PutIPAMvlansParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutIPAMvlansParamsWithHTTPClient(client *http.Client) *PutIPAMvlansParams {
	var ()
	return &PutIPAMvlansParams{
		HTTPClient: client,
	}
}

/*PutIPAMvlansParams contains all the parameters to send to the API endpoint
for the put IP a mvlans operation typically these are written to a http.Request
*/
type PutIPAMvlansParams struct {

	/*Description*/
	Description *string
	/*Groups
	  If multitenancy is on, admin groups that have access to this object are specified here, e.g. Prod_East:no,Corp:yes specifies that the admin groups for this object are Prod_East with view only permission and Corp with change permission. If this parameter is present with no value, all groups are deleted.

	*/
	Groups *string
	/*ID*/
	ID int64
	/*Name
	  If left blank, name will be created as VLANxxxx, e.g. VLAN# 342 will be named VLAN0342

	*/
	Name *string
	/*Notes
	  Any additional notes

	*/
	Notes *string
	/*Number
	  vlan number

	*/
	Number *string
	/*SwitchID
	  Comma separated values for switch_ids

	*/
	SwitchID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put IP a mvlans params
func (o *PutIPAMvlansParams) WithTimeout(timeout time.Duration) *PutIPAMvlansParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put IP a mvlans params
func (o *PutIPAMvlansParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put IP a mvlans params
func (o *PutIPAMvlansParams) WithContext(ctx context.Context) *PutIPAMvlansParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put IP a mvlans params
func (o *PutIPAMvlansParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put IP a mvlans params
func (o *PutIPAMvlansParams) WithHTTPClient(client *http.Client) *PutIPAMvlansParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put IP a mvlans params
func (o *PutIPAMvlansParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDescription adds the description to the put IP a mvlans params
func (o *PutIPAMvlansParams) WithDescription(description *string) *PutIPAMvlansParams {
	o.SetDescription(description)
	return o
}

// SetDescription adds the description to the put IP a mvlans params
func (o *PutIPAMvlansParams) SetDescription(description *string) {
	o.Description = description
}

// WithGroups adds the groups to the put IP a mvlans params
func (o *PutIPAMvlansParams) WithGroups(groups *string) *PutIPAMvlansParams {
	o.SetGroups(groups)
	return o
}

// SetGroups adds the groups to the put IP a mvlans params
func (o *PutIPAMvlansParams) SetGroups(groups *string) {
	o.Groups = groups
}

// WithID adds the id to the put IP a mvlans params
func (o *PutIPAMvlansParams) WithID(id int64) *PutIPAMvlansParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put IP a mvlans params
func (o *PutIPAMvlansParams) SetID(id int64) {
	o.ID = id
}

// WithName adds the name to the put IP a mvlans params
func (o *PutIPAMvlansParams) WithName(name *string) *PutIPAMvlansParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the put IP a mvlans params
func (o *PutIPAMvlansParams) SetName(name *string) {
	o.Name = name
}

// WithNotes adds the notes to the put IP a mvlans params
func (o *PutIPAMvlansParams) WithNotes(notes *string) *PutIPAMvlansParams {
	o.SetNotes(notes)
	return o
}

// SetNotes adds the notes to the put IP a mvlans params
func (o *PutIPAMvlansParams) SetNotes(notes *string) {
	o.Notes = notes
}

// WithNumber adds the number to the put IP a mvlans params
func (o *PutIPAMvlansParams) WithNumber(number *string) *PutIPAMvlansParams {
	o.SetNumber(number)
	return o
}

// SetNumber adds the number to the put IP a mvlans params
func (o *PutIPAMvlansParams) SetNumber(number *string) {
	o.Number = number
}

// WithSwitchID adds the switchID to the put IP a mvlans params
func (o *PutIPAMvlansParams) WithSwitchID(switchID *string) *PutIPAMvlansParams {
	o.SetSwitchID(switchID)
	return o
}

// SetSwitchID adds the switchId to the put IP a mvlans params
func (o *PutIPAMvlansParams) SetSwitchID(switchID *string) {
	o.SwitchID = switchID
}

// WriteToRequest writes these params to a swagger request
func (o *PutIPAMvlansParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Description != nil {

		// form param description
		var frDescription string
		if o.Description != nil {
			frDescription = *o.Description
		}
		fDescription := frDescription
		if fDescription != "" {
			if err := r.SetFormParam("description", fDescription); err != nil {
				return err
			}
		}

	}

	if o.Groups != nil {

		// form param groups
		var frGroups string
		if o.Groups != nil {
			frGroups = *o.Groups
		}
		fGroups := frGroups
		if fGroups != "" {
			if err := r.SetFormParam("groups", fGroups); err != nil {
				return err
			}
		}

	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if o.Name != nil {

		// form param name
		var frName string
		if o.Name != nil {
			frName = *o.Name
		}
		fName := frName
		if fName != "" {
			if err := r.SetFormParam("name", fName); err != nil {
				return err
			}
		}

	}

	if o.Notes != nil {

		// form param notes
		var frNotes string
		if o.Notes != nil {
			frNotes = *o.Notes
		}
		fNotes := frNotes
		if fNotes != "" {
			if err := r.SetFormParam("notes", fNotes); err != nil {
				return err
			}
		}

	}

	if o.Number != nil {

		// form param number
		var frNumber string
		if o.Number != nil {
			frNumber = *o.Number
		}
		fNumber := frNumber
		if fNumber != "" {
			if err := r.SetFormParam("number", fNumber); err != nil {
				return err
			}
		}

	}

	if o.SwitchID != nil {

		// form param switch_id
		var frSwitchID string
		if o.SwitchID != nil {
			frSwitchID = *o.SwitchID
		}
		fSwitchID := frSwitchID
		if fSwitchID != "" {
			if err := r.SetFormParam("switch_id", fSwitchID); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
