// Code generated by go-swagger; DO NOT EDIT.

package racks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetRacksIDParams creates a new GetRacksIDParams object
// with the default values initialized.
func NewGetRacksIDParams() *GetRacksIDParams {
	var ()
	return &GetRacksIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRacksIDParamsWithTimeout creates a new GetRacksIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRacksIDParamsWithTimeout(timeout time.Duration) *GetRacksIDParams {
	var ()
	return &GetRacksIDParams{

		timeout: timeout,
	}
}

// NewGetRacksIDParamsWithContext creates a new GetRacksIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRacksIDParamsWithContext(ctx context.Context) *GetRacksIDParams {
	var ()
	return &GetRacksIDParams{

		Context: ctx,
	}
}

// NewGetRacksIDParamsWithHTTPClient creates a new GetRacksIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRacksIDParamsWithHTTPClient(client *http.Client) *GetRacksIDParams {
	var ()
	return &GetRacksIDParams{
		HTTPClient: client,
	}
}

/*GetRacksIDParams contains all the parameters to send to the API endpoint
for the get racks ID operation typically these are written to a http.Request
*/
type GetRacksIDParams struct {

	/*ID
	  The ID of the rack to retrieve

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get racks ID params
func (o *GetRacksIDParams) WithTimeout(timeout time.Duration) *GetRacksIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get racks ID params
func (o *GetRacksIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get racks ID params
func (o *GetRacksIDParams) WithContext(ctx context.Context) *GetRacksIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get racks ID params
func (o *GetRacksIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get racks ID params
func (o *GetRacksIDParams) WithHTTPClient(client *http.Client) *GetRacksIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get racks ID params
func (o *GetRacksIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get racks ID params
func (o *GetRacksIDParams) WithID(id int64) *GetRacksIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get racks ID params
func (o *GetRacksIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetRacksIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param ID
	if err := r.SetPathParam("ID", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
