// Code generated by go-swagger; DO NOT EDIT.

package admin_users_groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAdminusersParams creates a new GetAdminusersParams object
// with the default values initialized.
func NewGetAdminusersParams() *GetAdminusersParams {

	return &GetAdminusersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAdminusersParamsWithTimeout creates a new GetAdminusersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAdminusersParamsWithTimeout(timeout time.Duration) *GetAdminusersParams {

	return &GetAdminusersParams{

		timeout: timeout,
	}
}

// NewGetAdminusersParamsWithContext creates a new GetAdminusersParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAdminusersParamsWithContext(ctx context.Context) *GetAdminusersParams {

	return &GetAdminusersParams{

		Context: ctx,
	}
}

// NewGetAdminusersParamsWithHTTPClient creates a new GetAdminusersParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAdminusersParamsWithHTTPClient(client *http.Client) *GetAdminusersParams {

	return &GetAdminusersParams{
		HTTPClient: client,
	}
}

/*GetAdminusersParams contains all the parameters to send to the API endpoint
for the get adminusers operation typically these are written to a http.Request
*/
type GetAdminusersParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get adminusers params
func (o *GetAdminusersParams) WithTimeout(timeout time.Duration) *GetAdminusersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get adminusers params
func (o *GetAdminusersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get adminusers params
func (o *GetAdminusersParams) WithContext(ctx context.Context) *GetAdminusersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get adminusers params
func (o *GetAdminusersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get adminusers params
func (o *GetAdminusersParams) WithHTTPClient(client *http.Client) *GetAdminusersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get adminusers params
func (o *GetAdminusersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAdminusersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
