// Code generated by go-swagger; DO NOT EDIT.

package admin_users_groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostAdminUsersParams creates a new PostAdminUsersParams object
// with the default values initialized.
func NewPostAdminUsersParams() *PostAdminUsersParams {
	var ()
	return &PostAdminUsersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostAdminUsersParamsWithTimeout creates a new PostAdminUsersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostAdminUsersParamsWithTimeout(timeout time.Duration) *PostAdminUsersParams {
	var ()
	return &PostAdminUsersParams{

		timeout: timeout,
	}
}

// NewPostAdminUsersParamsWithContext creates a new PostAdminUsersParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostAdminUsersParamsWithContext(ctx context.Context) *PostAdminUsersParams {
	var ()
	return &PostAdminUsersParams{

		Context: ctx,
	}
}

// NewPostAdminUsersParamsWithHTTPClient creates a new PostAdminUsersParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostAdminUsersParamsWithHTTPClient(client *http.Client) *PostAdminUsersParams {
	var ()
	return &PostAdminUsersParams{
		HTTPClient: client,
	}
}

/*PostAdminUsersParams contains all the parameters to send to the API endpoint
for the post admin users operation typically these are written to a http.Request
*/
type PostAdminUsersParams struct {

	/*Groups
	  Admin groups to assign user to. Note: groups with commas need to be wrapped in quotes. ie: “System Generated Read, Add, Edit and Delete”

	*/
	Groups *string
	/*Password
	  new user password

	*/
	Password string
	/*Username
	  admin user name

	*/
	Username string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post admin users params
func (o *PostAdminUsersParams) WithTimeout(timeout time.Duration) *PostAdminUsersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post admin users params
func (o *PostAdminUsersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post admin users params
func (o *PostAdminUsersParams) WithContext(ctx context.Context) *PostAdminUsersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post admin users params
func (o *PostAdminUsersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post admin users params
func (o *PostAdminUsersParams) WithHTTPClient(client *http.Client) *PostAdminUsersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post admin users params
func (o *PostAdminUsersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGroups adds the groups to the post admin users params
func (o *PostAdminUsersParams) WithGroups(groups *string) *PostAdminUsersParams {
	o.SetGroups(groups)
	return o
}

// SetGroups adds the groups to the post admin users params
func (o *PostAdminUsersParams) SetGroups(groups *string) {
	o.Groups = groups
}

// WithPassword adds the password to the post admin users params
func (o *PostAdminUsersParams) WithPassword(password string) *PostAdminUsersParams {
	o.SetPassword(password)
	return o
}

// SetPassword adds the password to the post admin users params
func (o *PostAdminUsersParams) SetPassword(password string) {
	o.Password = password
}

// WithUsername adds the username to the post admin users params
func (o *PostAdminUsersParams) WithUsername(username string) *PostAdminUsersParams {
	o.SetUsername(username)
	return o
}

// SetUsername adds the username to the post admin users params
func (o *PostAdminUsersParams) SetUsername(username string) {
	o.Username = username
}

// WriteToRequest writes these params to a swagger request
func (o *PostAdminUsersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Groups != nil {

		// form param groups
		var frGroups string
		if o.Groups != nil {
			frGroups = *o.Groups
		}
		fGroups := frGroups
		if fGroups != "" {
			if err := r.SetFormParam("groups", fGroups); err != nil {
				return err
			}
		}

	}

	// form param password
	frPassword := o.Password
	fPassword := frPassword
	if fPassword != "" {
		if err := r.SetFormParam("password", fPassword); err != nil {
			return err
		}
	}

	// form param username
	frUsername := o.Username
	fUsername := frUsername
	if fUsername != "" {
		if err := r.SetFormParam("username", fUsername); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
