// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeviceCustomerIDDeviceData device customer Id device data
//
// swagger:model deviceCustomerIdDeviceData
type DeviceCustomerIDDeviceData struct {

	// aliases
	Aliases []interface{} `json:"aliases"`

	// asset no
	AssetNo interface{} `json:"asset_no,omitempty"`

	// category
	Category interface{} `json:"category,omitempty"`

	// cpucore
	Cpucore interface{} `json:"cpucore,omitempty"`

	// cpucount
	Cpucount interface{} `json:"cpucount,omitempty"`

	// cpuspeed
	Cpuspeed interface{} `json:"cpuspeed,omitempty"`

	// custom fields
	CustomFields interface{} `json:"custom_fields,omitempty"`

	// customer
	Customer interface{} `json:"customer,omitempty"`

	// customer id
	CustomerID interface{} `json:"customer_id,omitempty"`

	// device external links
	DeviceExternalLinks interface{} `json:"device_external_links,omitempty"`

	// device purchase line items
	DevicePurchaseLineItems interface{} `json:"device_purchase_line_items,omitempty"`

	// hdd details
	HddDetails interface{} `json:"hdd_details,omitempty"`

	// hddcount
	Hddcount interface{} `json:"hddcount,omitempty"`

	// hddraid
	Hddraid interface{} `json:"hddraid,omitempty"`

	// hddraid type
	HddraidType interface{} `json:"hddraid_type,omitempty"`

	// hddsize
	Hddsize interface{} `json:"hddsize,omitempty"`

	// hw depth
	HwDepth interface{} `json:"hw_depth,omitempty"`

	// hw model
	HwModel interface{} `json:"hw_model,omitempty"`

	// hw size
	HwSize interface{} `json:"hw_size,omitempty"`

	// in service
	InService interface{} `json:"in_service,omitempty"`

	// ip addresses
	IPAddresses []*DeviceAllIPAddresses `json:"ip_addresses"`

	// last updated
	LastUpdated interface{} `json:"last_updated,omitempty"`

	// mac addresses
	MacAddresses []*DeviceCustomerIDMacAddresses `json:"mac_addresses"`

	// manufacturer
	Manufacturer interface{} `json:"manufacturer,omitempty"`

	// name
	Name interface{} `json:"name,omitempty"`

	// notes
	Notes interface{} `json:"notes,omitempty"`

	// os
	Os interface{} `json:"os,omitempty"`

	// ram
	RAM interface{} `json:"ram,omitempty"`

	// serial no
	SerialNo interface{} `json:"serial_no,omitempty"`

	// service level
	ServiceLevel interface{} `json:"service_level,omitempty"`

	// type
	Type interface{} `json:"type,omitempty"`

	// ucs manager
	UcsManager interface{} `json:"ucs_manager,omitempty"`

	// uuid
	UUID interface{} `json:"uuid,omitempty"`

	// virtual host name
	VirtualHostName interface{} `json:"virtual_host_name,omitempty"`
}

// Validate validates this device customer Id device data
func (m *DeviceCustomerIDDeviceData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateIPAddresses(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMacAddresses(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DeviceCustomerIDDeviceData) validateIPAddresses(formats strfmt.Registry) error {

	if swag.IsZero(m.IPAddresses) { // not required
		return nil
	}

	for i := 0; i < len(m.IPAddresses); i++ {
		if swag.IsZero(m.IPAddresses[i]) { // not required
			continue
		}

		if m.IPAddresses[i] != nil {
			if err := m.IPAddresses[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("ip_addresses" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *DeviceCustomerIDDeviceData) validateMacAddresses(formats strfmt.Registry) error {

	if swag.IsZero(m.MacAddresses) { // not required
		return nil
	}

	for i := 0; i < len(m.MacAddresses); i++ {
		if swag.IsZero(m.MacAddresses[i]) { // not required
			continue
		}

		if m.MacAddresses[i] != nil {
			if err := m.MacAddresses[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("mac_addresses" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *DeviceCustomerIDDeviceData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeviceCustomerIDDeviceData) UnmarshalBinary(b []byte) error {
	var res DeviceCustomerIDDeviceData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
