// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IPMtapPorts IP mtap ports
//
// swagger:model IPMtap_ports
type IPMtapPorts struct {

	// id
	ID interface{} `json:"id,omitempty"`

	// label
	Label interface{} `json:"label,omitempty"`

	// mac
	Mac interface{} `json:"mac,omitempty"`

	// mirror port id
	MirrorPortID interface{} `json:"mirror_port_id,omitempty"`

	// module
	Module interface{} `json:"module,omitempty"`

	// module id
	ModuleID interface{} `json:"module_id,omitempty"`

	// monitor direction
	MonitorDirection interface{} `json:"monitor_direction,omitempty"`

	// monitor port 1 id
	MonitorPort1ID interface{} `json:"monitor_port_1_id,omitempty"`

	// monitor port 2 id
	MonitorPort2ID interface{} `json:"monitor_port_2_id,omitempty"`

	// netport id
	NetportID interface{} `json:"netport_id,omitempty"`

	// port capability
	PortCapability interface{} `json:"port_capability,omitempty"`

	// port to from id
	PortToFromID interface{} `json:"port_to_from_id,omitempty"`

	// port type
	PortType interface{} `json:"port_type,omitempty"`

	// port type id
	PortTypeID interface{} `json:"port_type_id,omitempty"`

	// tap
	Tap interface{} `json:"tap,omitempty"`

	// tap id
	TapID interface{} `json:"tap_id,omitempty"`
}

// Validate validates this IP mtap ports
func (m *IPMtapPorts) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IPMtapPorts) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IPMtapPorts) UnmarshalBinary(b []byte) error {
	var res IPMtapPorts
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
